### ISSUE TITLE
Fix bugs/problems revealed by unit tests

### ISSUE THREAD

**Issue by nsoblath** [driplineorg/dripline#19]
- [x] driplineorg/dripline-python#59
- [x] driplineorg/dripline-python#63
- [x] driplineorg/dripline-python#64
- [x] driplineorg/dripline-python#66

**Comment by laroque** [comment]
These issues are all resolved on various branches, but merging them is awaiting a new release of dripline-cpp with other fixes from earlier today.
